# Generated by Django 5.2.6 on 2025-12-28 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=50, verbose_name='Название экскурсии')),
                ('tour_description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Минимальная длина описания - 10 символов')], verbose_name='Описание экскурсии')),
                ('tour_img', models.ImageField(blank=True, null=True, upload_to='tours_media/tours_img')),
                ('tour_content_type', models.CharField(default='Экскурсия', editable=False, max_length=10)),
                ('tour_created_time', models.TimeField(auto_now=True, verbose_name='Время создания')),
                ('tour_created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_tour_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['-tour_created_date'],
            },
        ),
        migrations.CreateModel(
            name='TourDropDownElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100, verbose_name='Название элемента экскурсии')),
                ('element_description', models.TextField(blank=True, verbose_name='Описание элемента экскурсии')),
                ('element_icon', models.ImageField(blank=True, null=True, upload_to='tour_el_media/icons')),
                ('element_created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания элемента экскурсии')),
                ('element_img', models.ImageField(blank=True, null=True, upload_to='tour_el_media/photo', verbose_name='Фото')),
                ('element_video', models.FileField(blank=True, null=True, upload_to='tour_el_media/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_down_elements', to='miniapp_demo_tg.tour', verbose_name='Элементы экскурсии')),
            ],
            options={
                'verbose_name': 'Элемент выпадающего списка',
                'verbose_name_plural': 'Элементы выпадающего списка',
                'ordering': ['element_created_at', 'element_name'],
            },
        ),
    ]
