# Generated by Django 5.2.6 on 2025-12-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp_demo_tg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TG_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(default='user_name', max_length=64)),
                ('second_name', models.CharField(max_length=64, null=True)),
                ('user_icon', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
